# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew Zhang
email: zhangmhao@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello!
  I'm Andrew Zhange, a front-end developer who believes the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# other links
# twitter_username: gaohaoyang126
# facebook_username: gaohaoyang.water
twitter_username: jekyllrb
github_username:  zhangmhao
email: zhangmhao@gmail.com
zhihu_username: zhang-an-37
# linkedIn_username:
# dribbble_username:

description_footer: Hi, I'm Andrew, A Senior Front-end Developer with 7 years of professional experience. I believe web is the foundation of Internet. Now I'm working at Alibaba, base in Shenzhen China.


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /:year/:month/:day/:title/


# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: #hygblog
# disqus_shortname: gaohaoyang

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
# baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
# google_analytics_id: UA-72449510-4 # google 分析追踪id


# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6

